import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { apiPlugin, setComponents, storyblokInit } from '@storyblok/react/rsc';
import { StoryblokProvider } from './components/StoryblokProvider';
import Tour from './components/Tour';
import Page from './components/Page';
import Hero from './components/Hero';
import Grid from './components/Grid';
import Feature from './components/Feature';
import Testimonial from './components/Testimonial';
import RecommendedTours from './components/RecommendedTours';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const storyblokComponents = {
  tour: Tour,
  page: Page,
  hero: Hero,
  grid: Grid,
  feature: Feature,
  testimonial: Testimonial,
  recommended_tours: RecommendedTours,
};

storyblokInit({
  accessToken: process.env.STORYBLOK_TOKEN,
  use: [apiPlugin],
  components: storyblokComponents,
  enableFallbackComponent: true,
});
setComponents(storyblokComponents);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col bg-blue-50">
          <header>
            <nav className="container mx-auto px-4 w-full py-8 flex justify-between">
              <Link href="/">Home</Link>
              <Link href="/tours">Tours</Link>
            </nav>
          </header>
          {children}
        </body>
      </html>
    </StoryblokProvider>
  );
}
